import type { Operation } from '../core/types';
export const operations: Record<string, Operation> = {
  'ConfigService.ListUserAccounts': {
    id: 'ConfigService.ListUserAccounts',
    title: 'List User Accounts',
    method: 'GET',
    path: '/Config/ListPaymentAccounts',
    query: {},
    fields: [],
    read: true,
  },
  'ConfigService.ListCalculationType': {
    id: 'ConfigService.ListCalculationType',
    title: 'List Calculation Type',
    method: 'GET',
    path: '/Config/ListCalCulationType',
    query: {},
    fields: [],
    read: true,
  },
  'ConfigService.ListChargeDeductionType': {
    id: 'ConfigService.ListChargeDeductionType',
    title: 'List Charge Deduction Type',
    method: 'GET',
    path: '/Config/ListChargeDedcutionType',
    query: {},
    fields: [],
    read: true,
  },
  'ConfigService.ListPlan': {
    id: 'ConfigService.ListPlan',
    title: 'List Plan',
    method: 'GET',
    path: '/Config/ListPlanMaster',
    query: {},
    fields: [],
    read: true,
  },
  'ConfigService.ListSlabType': {
    id: 'ConfigService.ListSlabType',
    title: 'List Slab Type',
    method: 'GET',
    path: '/Config/GetallSlabType',
    query: {},
    fields: [],
    read: true,
  },
  'ConfigService.ListCommissionDistribution': {
    id: 'ConfigService.ListCommissionDistribution',
    title: 'List Commission Distribution',
    method: 'POST',
    path: '/Config/ListCommissionDistribution',
    query: {},
    fields: [
      {
        name: 'AgencyId',
        label: 'Agency ID',
        type: 'number',
        required: false,
      },
      {
        name: 'ServiceId',
        label: 'Service ID',
        type: 'number',
        required: false,
      },
      {
        name: 'CalculationTypeId',
        label: 'Calculation Type ID',
        type: 'number',
        required: false,
      },
      {
        name: 'amount',
        label: 'Amount',
        type: 'number',
        required: false,
      },
      {
        name: 'PlanId',
        label: 'Plan ID',
        type: 'number',
        required: false,
      },
    ],
    read: true,
  },
  'ConfigService.ListTopupCharge': {
    id: 'ConfigService.ListTopupCharge',
    title: 'List Topup Charge',
    method: 'POST',
    path: '/Config/ListTopupCharge',
    query: {},
    fields: [
      {
        name: 'TopupChargeId',
        label: 'Topup Charge ID',
        type: 'number',
        required: false,
      },
      {
        name: 'SlabTypeId',
        label: 'Slab Type ID',
        type: 'number',
        required: false,
      },
      {
        name: 'CalculationTypeId',
        label: 'Calculation Type ID',
        type: 'number',
        required: false,
      },
      {
        name: 'Amount',
        label: 'Amount',
        type: 'number',
        required: false,
      },
    ],
    read: true,
  },
  'ConfigService.ListTransactionslab': {
    id: 'ConfigService.ListTransactionslab',
    title: 'List Transactionslab',
    method: 'POST',
    path: '/Config/ListTransactionSlab',
    query: {},
    fields: [
      {
        name: 'PlanId',
        label: 'Plan ID',
        type: 'number',
        required: true,
      },
      {
        name: 'SlabId',
        label: 'Slab ID',
        type: 'number',
        required: false,
      },
      {
        name: 'SlabType',
        label: 'Slab Type',
        type: 'number',
        required: false,
      },
      {
        name: 'CalculationType',
        label: 'Calculation Type',
        type: 'number',
        required: false,
      },
      {
        name: 'AgencyID',
        label: 'Agency ID',
        type: 'number',
        required: false,
      },
      {
        name: 'ServiceID',
        label: 'Service ID',
        type: 'number',
        required: false,
      },
      {
        name: 'Amount',
        label: 'Amount',
        type: 'number',
        required: false,
      },
    ],
    read: true,
  },
  'ConfigService.AddCompanyPaymentAccount': {
    id: 'ConfigService.AddCompanyPaymentAccount',
    title: 'Add Company Payment Account',
    method: 'POST',
    path: '/Config/AddPaymentAccounts',
    query: {},
    fields: [
      {
        name: 'BankID',
        label: 'Bank ID',
        type: 'number',
        required: false,
      },
      {
        name: 'AccountName',
        label: 'Account Name',
        type: 'string',
        required: true,
      },
      {
        name: 'AccountNo',
        label: 'Account No',
        type: 'string',
        required: true,
      },
      {
        name: 'Ifsccode',
        label: 'Ifsccode',
        type: 'string',
        required: true,
      },
      {
        name: 'BranchName',
        label: 'Branch Name',
        type: 'string',
        required: true,
      },
      {
        name: 'Branchcode',
        label: 'Branchcode',
        type: 'string',
        required: true,
      },
      {
        name: 'Micrcode',
        label: 'Micrcode',
        type: 'string',
        required: true,
      },
      {
        name: 'BranchAddress',
        label: 'Branch Address',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'ConfigService.ChangeAccPaymentStatus': {
    id: 'ConfigService.ChangeAccPaymentStatus',
    title: 'Change Acc Payment Status',
    method: 'POST',
    path: '/Config/changesPaymentAccountsStatus',
    query: {},
    fields: [
      {
        name: 'PaymentAccountID',
        label: 'Payment Account ID',
        type: 'number',
        required: false,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: false,
      },
      {
        name: 'Remarks',
        label: 'Remarks',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'ConfigService.AddNewTransactionSlab': {
    id: 'ConfigService.AddNewTransactionSlab',
    title: 'Add New Transaction Slab',
    method: 'POST',
    path: '/Config/AddTransacttionSlab',
    query: {},
    fields: [
      {
        name: 'PlanId',
        label: 'Plan ID',
        type: 'number',
        required: true,
      },
      {
        name: 'AgencyID',
        label: 'Agency ID',
        type: 'number',
        required: true,
      },
      {
        name: 'ServiceID',
        label: 'Service ID',
        type: 'number',
        required: true,
      },
      {
        name: 'FromAmount',
        label: 'From Amount',
        type: 'number',
        required: true,
      },
      {
        name: 'ToAmount',
        label: 'To Amount',
        type: 'number',
        required: true,
      },
      {
        name: 'SlabType',
        label: 'Slab Type',
        type: 'number',
        required: true,
      },
      {
        name: 'CalculationType',
        label: 'Calculation Type',
        type: 'number',
        required: true,
      },
      {
        name: 'CalculationValue',
        label: 'Calculation Value',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'ReportmanService.PayoutTransactionReport': {
    id: 'ReportmanService.PayoutTransactionReport',
    title: 'Payout Transaction Report',
    method: 'POST',
    path: '/Transaction/GetAllPayoutTransaction',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'TransactionCode',
        label: 'Transaction Code',
        type: 'string',
        required: true,
      },
      {
        name: 'TxnType',
        label: 'Txn Type',
        type: 'string',
        required: true,
      },
      {
        name: 'PartnerTransactionId',
        label: 'Partner Transaction ID',
        type: 'string',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
      {
        name: 'FromDate',
        label: 'From Date',
        type: 'string',
        required: false,
      },
      {
        name: 'ToDate',
        label: 'To Date',
        type: 'string',
        required: false,
      },
    ],
    read: true,
  },
  'ReportmanService.ListUserStatement': {
    id: 'ReportmanService.ListUserStatement',
    title: 'List User Statement',
    method: 'POST',
    path: '/Transaction/GetUSerStatement',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'FromDate',
        label: 'From Date',
        type: 'string',
        required: false,
      },
      {
        name: 'ToDate',
        label: 'To Date',
        type: 'string',
        required: false,
      },
    ],
    read: true,
  },
  'ReportmanService.GetTransactionSummaryByUserId': {
    id: 'ReportmanService.GetTransactionSummaryByUserId',
    title: 'Get Transaction Summary By User ID',
    method: 'GET',
    path: '/Report/GetTransactionSummaryByUserId',
    query: {
      UserID: 'Userid',
    },
    fields: [
      {
        name: 'Userid',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'ReportmanService.GetDayBookByUserId': {
    id: 'ReportmanService.GetDayBookByUserId',
    title: 'Get Day Book By User ID',
    method: 'POST',
    path: '/Transaction/GetDayBookByUserId',
    query: {},
    fields: [
      {
        name: 'UserID',
        label: 'User ID',
        type: 'number',
        required: true,
      },
      {
        name: 'FromDate',
        label: 'From Date',
        type: 'string',
        required: false,
      },
      {
        name: 'ToDate',
        label: 'To Date',
        type: 'string',
        required: false,
      },
    ],
    read: true,
  },
  'ReportmanService.GetallFirmDetail': {
    id: 'ReportmanService.GetallFirmDetail',
    title: 'List Firm Detail',
    method: 'GET',
    path: '/Report/GetallFirmDetail',
    query: {
      UserID: 'Userid',
    },
    fields: [
      {
        name: 'Userid',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'TransactionsService.AddPayinRequest': {
    id: 'TransactionsService.AddPayinRequest',
    title: 'Add Payin Request',
    method: 'POST',
    path: '/Transaction/NewPayinRequest',
    query: {},
    fields: [
      {
        name: 'PaymentChanelID',
        label: 'Payment Chanel ID',
        type: 'number',
        required: true,
      },
      {
        name: 'PaymentModeId',
        label: 'Payment Mode ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Amount',
        label: 'Amount',
        type: 'number',
        required: false,
      },
      {
        name: 'Charge',
        label: 'Charge',
        type: 'number',
        required: false,
      },
      {
        name: 'OriginatorAccountId',
        label: 'Originator Account ID',
        type: 'number',
        required: true,
      },
      {
        name: 'BenficiaryAccountId',
        label: 'Benficiary Account ID',
        type: 'number',
        required: true,
      },
      {
        name: 'DepositDate',
        label: 'Deposit Date',
        type: 'string',
        required: false,
      },
      {
        name: 'RefNo1',
        label: 'Ref No1',
        type: 'string',
        required: false,
      },
      {
        name: 'RefNo2',
        label: 'Ref No2',
        type: 'string',
        required: false,
      },
      {
        name: 'Remarks',
        label: 'Remarks',
        type: 'string',
        required: false,
      },
    ],
    read: false,
  },
  'TransactionsService.ListPaymentResponse': {
    id: 'TransactionsService.ListPaymentResponse',
    title: 'List Payment Response',
    method: 'POST',
    path: '/Transaction/ListPayinRequest',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'PaymentChanelID',
        label: 'Payment Chanel ID',
        type: 'number',
        required: true,
      },
      {
        name: 'PaymentModeId',
        label: 'Payment Mode ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
      {
        name: 'FromDate',
        label: 'From Date',
        type: 'string',
        required: false,
      },
      {
        name: 'ToDate',
        label: 'To Date',
        type: 'string',
        required: false,
      },
    ],
    read: true,
  },
  'TransactionsService.GetPayinRecieptFiles': {
    id: 'TransactionsService.GetPayinRecieptFiles',
    title: 'Get Payin Reciept Files',
    method: 'GET',
    path: '/Transaction/DocumentViewPauinrequest_Search',
    query: {
      RequestID: 'RequestID',
    },
    fields: [
      {
        name: 'RequestID',
        label: 'Request ID',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'TransactionsService.ListPayinAccListResponse': {
    id: 'TransactionsService.ListPayinAccListResponse',
    title: 'List Payin Acc List Response',
    method: 'POST',
    path: '/User/ListallOriginatorsAccounts',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'TransactionsService.GetPayinAccChequeFiles': {
    id: 'TransactionsService.GetPayinAccChequeFiles',
    title: 'Get Payin Acc Cheque Files',
    method: 'GET',
    path: '/User/GetOriginatorChequePhoto',
    query: {
      AccountID: 'RequestID',
    },
    fields: [
      {
        name: 'RequestID',
        label: 'Account ID',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'TransactionsService.ChangePayinRequestStatus': {
    id: 'TransactionsService.ChangePayinRequestStatus',
    title: 'Change Payin Request Status',
    method: 'POST',
    path: '/Transaction/ChangePayinRequestStatus',
    query: {},
    fields: [
      {
        name: 'RequestID',
        label: 'Request ID',
        type: 'number',
        required: true,
      },
      {
        name: 'RejectedReason',
        label: 'Rejected Reason',
        type: 'string',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'TransactionsService.ListPayinAccListforAdminResponse': {
    id: 'TransactionsService.ListPayinAccListforAdminResponse',
    title: 'List Payin Acc Listfor Admin Response',
    method: 'POST',
    path: '/User/ListAllOriginatorsAccountsforAdmin',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
      {
        name: 'FromDate',
        label: 'From Date',
        type: 'string',
        required: false,
      },
      {
        name: 'ToDate',
        label: 'To Date',
        type: 'string',
        required: false,
      },
    ],
    read: true,
  },
  'TransactionsService.ApproveRejectPayinAccounts': {
    id: 'TransactionsService.ApproveRejectPayinAccounts',
    title: 'Approve Reject Payin Accounts',
    method: 'POST',
    path: '/User/ApproveRejectOrigiAccounts',
    query: {},
    fields: [
      {
        name: 'RequestId',
        label: 'Request ID',
        type: 'number',
        required: true,
      },
      {
        name: 'RemarksReason',
        label: 'Remarks Reason',
        type: 'string',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.UserOnboarding': {
    id: 'UserMasterService.UserOnboarding',
    title: 'User Onboarding',
    method: 'POST',
    path: '/User/CreateNewUser',
    query: {},
    fields: [
      {
        name: 'UserTypeId',
        label: 'User Type ID',
        type: 'number',
        required: true,
      },
      {
        name: 'MobileNo',
        label: 'Mobile No',
        type: 'string',
        required: true,
      },
      {
        name: 'EmailId',
        label: 'Email ID',
        type: 'string',
        required: true,
      },
      {
        name: 'FirstName',
        label: 'First Name',
        type: 'string',
        required: true,
      },
      {
        name: 'MiddleName',
        label: 'Middle Name',
        type: 'string',
        required: true,
      },
      {
        name: 'LastName',
        label: 'Last Name',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.UploadUserLogo': {
    id: 'UserMasterService.UploadUserLogo',
    title: 'Upload User Logo',
    method: 'POST',
    path: '/User/UploadUserLogo',
    query: {},
    fields: [
      {
        name: 'file',
        label: 'File',
        type: 'file',
        required: true,
      },
    ],
    read: false,
    multipart: true,
  },
  'UserMasterService.AddUserAccounts': {
    id: 'UserMasterService.AddUserAccounts',
    title: 'Add User Accounts',
    method: 'POST',
    path: '/User/AddOriginatorAccounts',
    query: {},
    fields: [
      {
        name: 'bankId',
        label: 'Bank ID',
        type: 'number',
        required: true,
      },
      {
        name: 'accountName',
        label: 'Account Name',
        type: 'string',
        required: true,
      },
      {
        name: 'accountNo',
        label: 'Account No',
        type: 'string',
        required: true,
      },
      {
        name: 'ifsccode',
        label: 'Ifsccode',
        type: 'string',
        required: true,
      },
      {
        name: 'branchAddress',
        label: 'Branch Address',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ListUserAccounts': {
    id: 'UserMasterService.ListUserAccounts',
    title: 'List User Accounts',
    method: 'GET',
    path: '/User/ListOriginatorAccounts',
    query: {},
    fields: [],
    read: true,
  },
  'UserMasterService.AddUserAddress': {
    id: 'UserMasterService.AddUserAddress',
    title: 'Add User Address',
    method: 'POST',
    path: '/User/AddUserAddress',
    query: {},
    fields: [
      {
        name: 'userId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
      {
        name: 'AddressTypeId',
        label: 'Address Type ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Pincode',
        label: 'Pincode',
        type: 'string',
        required: true,
      },
      {
        name: 'Address1',
        label: 'Address1',
        type: 'string',
        required: true,
      },
      {
        name: 'Address2',
        label: 'Address2',
        type: 'string',
        required: true,
      },
      {
        name: 'Address3',
        label: 'Address3',
        type: 'string',
        required: true,
      },
      {
        name: 'PincodeDataId',
        label: 'Pincode Data ID',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ListUserAddresses': {
    id: 'UserMasterService.ListUserAddresses',
    title: 'List User Addresses',
    method: 'GET',
    path: '/User/ListUserAddresses',
    query: {},
    fields: [],
    read: true,
  },
  'UserMasterService.AddUserDeatilKYC': {
    id: 'UserMasterService.AddUserDeatilKYC',
    title: 'Add User Deatil KYC',
    method: 'POST',
    path: '/User/AddUserDeatilKYC',
    query: {},
    fields: [
      {
        name: 'userId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
      {
        name: 'documentNo',
        label: 'Document No',
        type: 'string',
        required: true,
      },
      {
        name: 'fileUrl',
        label: 'File Url',
        type: 'string',
        required: true,
      },
      {
        name: 'kycID',
        label: 'Kyc ID',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ListUserKYC': {
    id: 'UserMasterService.ListUserKYC',
    title: 'List User KYC',
    method: 'GET',
    path: '/User/ListUserKYC',
    query: {},
    fields: [],
    read: true,
  },
  'UserMasterService.ListUserKYCByUserId': {
    id: 'UserMasterService.ListUserKYCByUserId',
    title: 'List User KYCBy User ID',
    method: 'GET',
    path: '/User/ListUserKYCByUserId',
    query: {
      UserId: 'UserId',
    },
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.ListApplication': {
    id: 'UserMasterService.ListApplication',
    title: 'List Application',
    method: 'GET',
    path: '/User/GetAllapplication',
    query: {},
    fields: [],
    read: true,
  },
  'UserMasterService.CreateNewApplication': {
    id: 'UserMasterService.CreateNewApplication',
    title: 'Create New Application',
    method: 'POST',
    path: '/Config/CreateNewApplication',
    query: {},
    fields: [
      {
        name: 'ApplicationName',
        label: 'Application Name',
        type: 'string',
        required: true,
      },
      {
        name: 'ApplicationDescription',
        label: 'Application Description',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ListUsers': {
    id: 'UserMasterService.ListUsers',
    title: 'List Users',
    method: 'GET',
    path: '/User/GetallUserByOrg',
    query: {},
    fields: [],
    read: true,
  },
  'UserMasterService.CreateNewUserData': {
    id: 'UserMasterService.CreateNewUserData',
    title: 'Create New User Data',
    method: 'POST',
    path: '/User/CreateNewAPIUser',
    query: {},
    fields: [
      {
        name: 'EmailId',
        label: 'Email ID',
        type: 'string',
        required: true,
      },
      {
        name: 'MobileNo',
        label: 'Mobile No',
        type: 'string',
        required: true,
      },
      {
        name: 'applicationID',
        label: 'Application ID',
        type: 'number',
        required: true,
      },
      {
        name: 'UserTypeId',
        label: 'User Type ID',
        type: 'number',
        required: true,
      },
      {
        name: 'FirstName',
        label: 'First Name',
        type: 'string',
        required: true,
      },
      {
        name: 'LastName',
        label: 'Last Name',
        type: 'string',
        required: true,
      },
      {
        name: 'Password',
        label: 'Password',
        type: 'string',
        required: true,
      },
      {
        name: 'AccessID',
        label: 'Access ID',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ListUserKYCByID': {
    id: 'UserMasterService.ListUserKYCByID',
    title: 'List User KYCBy ID',
    method: 'GET',
    path: '/User/ListUserKYCById',
    query: {
      KycId: 'kycid',
    },
    fields: [
      {
        name: 'kycid',
        label: 'Kyc ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.DocumentView_Search': {
    id: 'UserMasterService.DocumentView_Search',
    title: 'Document View Search',
    method: 'GET',
    path: '/User/DocumentView_Search',
    query: {
      KYCID: 'kycid',
    },
    fields: [
      {
        name: 'kycid',
        label: 'KYCID',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ListAllAppMenu': {
    id: 'UserMasterService.ListAllAppMenu',
    title: 'List All App Menu',
    method: 'GET',
    path: '/User/ListAllMenu',
    query: {},
    fields: [],
    read: true,
  },
  'UserMasterService.ListAllAppSubMenu': {
    id: 'UserMasterService.ListAllAppSubMenu',
    title: 'List All App Sub Menu',
    method: 'GET',
    path: '/User/ListAllsubMenu',
    query: {
      Menuid: 'Menuid',
    },
    fields: [
      {
        name: 'Menuid',
        label: 'Menuid',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.GetOrganisationDetails': {
    id: 'UserMasterService.GetOrganisationDetails',
    title: 'Get Organisation Details',
    method: 'GET',
    path: '/User/GetAllUserDetails',
    query: {},
    fields: [],
    read: true,
  },
  'UserMasterService.ListOrganisationDetails': {
    id: 'UserMasterService.ListOrganisationDetails',
    title: 'List Organisation Details',
    method: 'POST',
    path: '/User/GetAllOrganisationDetails',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'MobileNo',
        label: 'Mobile No',
        type: 'string',
        required: true,
      },
      {
        name: 'EmailId',
        label: 'Email ID',
        type: 'string',
        required: true,
      },
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.ApproveRejectUserdoc': {
    id: 'UserMasterService.ApproveRejectUserdoc',
    title: 'Approve Reject Userdoc',
    method: 'POST',
    path: '/User/ApproveRejectUserDocument',
    query: {},
    fields: [
      {
        name: 'UserKYCID',
        label: 'User KYCID',
        type: 'number',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
      {
        name: 'RejectedReason',
        label: 'Rejected Reason',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.GetAllUserConfigration': {
    id: 'UserMasterService.GetAllUserConfigration',
    title: 'List User Configration',
    method: 'GET',
    path: '/User/GetAllUserConfigration',
    query: {
      UserId: 'UserId',
    },
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.UpdateUserconfiguration': {
    id: 'UserMasterService.UpdateUserconfiguration',
    title: 'Update Userconfiguration',
    method: 'POST',
    path: '/User/UpDateUserConfigrationDetails',
    query: {},
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
      {
        name: 'MinTxn',
        label: 'Min Txn',
        type: 'number',
        required: true,
      },
      {
        name: 'MaxTxn',
        label: 'Max Txn',
        type: 'number',
        required: true,
      },
      {
        name: 'ChargeTypeOn',
        label: 'Charge Type On',
        type: 'number',
        required: true,
      },
      {
        name: 'MaxPayinAmount',
        label: 'Max Payin Amount',
        type: 'number',
        required: true,
      },
      {
        name: 'MaxNoOfCountPayin',
        label: 'Max No Of Count Payin',
        type: 'number',
        required: true,
      },
      {
        name: 'SameAmountPayinAllowed',
        label: 'Same Amount Payin Allowed',
        type: 'number',
        required: true,
      },
      {
        name: 'PlanId',
        label: 'Plan ID',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ActivateDeactivateApiUser': {
    id: 'UserMasterService.ActivateDeactivateApiUser',
    title: 'Activate Deactivate Api User',
    method: 'POST',
    path: '/User/ActivateDeactivateApiUser',
    query: {},
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
      {
        name: 'Reason',
        label: 'Reason',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ActivateDeactivateUserMaster': {
    id: 'UserMasterService.ActivateDeactivateUserMaster',
    title: 'Activate Deactivate User Master',
    method: 'POST',
    path: '/User/ActivateDeactivateUserMaster',
    query: {},
    fields: [
      {
        name: 'UserMasterId',
        label: 'User Master ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
      {
        name: 'Reason',
        label: 'Reason',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.GetAllUserMasterList': {
    id: 'UserMasterService.GetAllUserMasterList',
    title: 'List User Master List',
    method: 'POST',
    path: '/User/GetAllUserMasterList',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'MobileNo',
        label: 'Mobile No',
        type: 'string',
        required: true,
      },
      {
        name: 'EmailId',
        label: 'Email ID',
        type: 'string',
        required: true,
      },
      {
        name: 'UserMasterId',
        label: 'User Master ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.ListUserAddress': {
    id: 'UserMasterService.ListUserAddress',
    title: 'List User Address',
    method: 'POST',
    path: '/User/ListUserAddress',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.ChangePassword': {
    id: 'UserMasterService.ChangePassword',
    title: 'Change Password',
    method: 'POST',
    path: '/User/ChangePassword',
    query: {},
    fields: [
      {
        name: 'UserName',
        label: 'User Name',
        type: 'string',
        required: true,
      },
      {
        name: 'Password',
        label: 'Password',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.AddIPAddress': {
    id: 'UserMasterService.AddIPAddress',
    title: 'Add IPAddress',
    method: 'POST',
    path: '/User/AddIPAddress',
    query: {},
    fields: [
      {
        name: 'IPAddress',
        label: 'IPAddress',
        type: 'string',
        required: true,
      },
      {
        name: 'ApplicationId',
        label: 'Application ID',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.GetallUserIPAddress': {
    id: 'UserMasterService.GetallUserIPAddress',
    title: 'List User IPAddress',
    method: 'GET',
    path: '/User/GetallIPAdress',
    query: {
      UserId: 'UserId',
    },
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.ApproveRejectIP': {
    id: 'UserMasterService.ApproveRejectIP',
    title: 'Approve Reject IP',
    method: 'POST',
    path: '/User/ApproveRejectIP',
    query: {},
    fields: [
      {
        name: 'IpAddressId',
        label: 'Ip Address ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ListAllIPAddress': {
    id: 'UserMasterService.ListAllIPAddress',
    title: 'List All IPAddress',
    method: 'POST',
    path: '/User/GetAllIPAddressforAdmin',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
      {
        name: 'applicationID',
        label: 'Application ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.ListApplicationForAdmin': {
    id: 'UserMasterService.ListApplicationForAdmin',
    title: 'List Application For Admin',
    method: 'GET',
    path: '/User/GetAllapplicationForAdmin',
    query: {
      UserId: 'UserId',
    },
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.GetUserLogo': {
    id: 'UserMasterService.GetUserLogo',
    title: 'Get User Logo',
    method: 'GET',
    path: '/User/GetUserLogo',
    query: {
      UserId: 'UserId',
    },
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.GetUserOtherDetails': {
    id: 'UserMasterService.GetUserOtherDetails',
    title: 'Get User Other Details',
    method: 'GET',
    path: '/User/GetUserOtherDetails',
    query: {
      UserId: 'UserId',
    },
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'UserMasterService.AddUserOtherDetails': {
    id: 'UserMasterService.AddUserOtherDetails',
    title: 'Add User Other Details',
    method: 'POST',
    path: '/User/AddUserOtherDetails',
    query: {},
    fields: [
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Pancard',
        label: 'Pancard',
        type: 'string',
        required: true,
      },
      {
        name: 'AadharCard',
        label: 'Aadhar Card',
        type: 'string',
        required: true,
      },
      {
        name: 'GstNo',
        label: 'Gst No',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.AddNewOutlet': {
    id: 'UserMasterService.AddNewOutlet',
    title: 'Add New Outlet',
    method: 'POST',
    path: '/User/AddNewOutLet',
    query: {},
    fields: [
      {
        name: 'UserTypeId',
        label: 'User Type ID',
        type: 'number',
        required: true,
      },
      {
        name: 'FirstName',
        label: 'First Name',
        type: 'string',
        required: true,
      },
      {
        name: 'MiddleName',
        label: 'Middle Name',
        type: 'string',
        required: true,
      },
      {
        name: 'LastName',
        label: 'Last Name',
        type: 'string',
        required: true,
      },
      {
        name: 'GenderID',
        label: 'Gender ID',
        type: 'number',
        required: true,
      },
      {
        name: 'OrganisationName',
        label: 'Organisation Name',
        type: 'string',
        required: true,
      },
      {
        name: 'MobileNo',
        label: 'Mobile No',
        type: 'string',
        required: true,
      },
      {
        name: 'EmailId',
        label: 'Email ID',
        type: 'string',
        required: true,
      },
      {
        name: 'ParentID',
        label: 'Parent ID',
        type: 'number',
        required: true,
      },
    ],
    read: false,
  },
  'UserMasterService.ListAllOutltes': {
    id: 'UserMasterService.ListAllOutltes',
    title: 'List All Outltes',
    method: 'POST',
    path: '/User/GetAllOutLetList',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'MobileNo',
        label: 'Mobile No',
        type: 'string',
        required: true,
      },
      {
        name: 'Usercode',
        label: 'Usercode',
        type: 'string',
        required: true,
      },
      {
        name: 'EmailId',
        label: 'Email ID',
        type: 'string',
        required: true,
      },
      {
        name: 'UserId',
        label: 'User ID',
        type: 'number',
        required: false,
      },
      {
        name: 'ParentID',
        label: 'Parent ID',
        type: 'number',
        required: false,
      },
      {
        name: 'UserTypeId',
        label: 'User Type ID',
        type: 'number',
        required: false,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: false,
      },
      {
        name: 'ParentCode',
        label: 'Parent Code',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'LoginServiceService.login': {
    id: 'LoginServiceService.login',
    title: 'Login',
    method: 'POST',
    path: '/AA/login',
    query: {},
    fields: [
      {
        name: 'Username',
        label: 'Username',
        type: 'string',
        required: true,
      },
      {
        name: 'Password',
        label: 'Password',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'LoginServiceService.RegisterUser': {
    id: 'LoginServiceService.RegisterUser',
    title: 'Register User',
    method: 'POST',
    path: '/User/CreateOrgAPIPartner',
    query: {},
    fields: [
      {
        name: 'EmailId',
        label: 'Email ID',
        type: 'string',
        required: false,
      },
      {
        name: 'MobileNo',
        label: 'Mobile No',
        type: 'string',
        required: false,
      },
      {
        name: 'OrganisationName',
        label: 'Organisation Name',
        type: 'string',
        required: false,
      },
      {
        name: 'FirstName',
        label: 'First Name',
        type: 'string',
        required: false,
      },
      {
        name: 'LastName',
        label: 'Last Name',
        type: 'string',
        required: false,
      },
      {
        name: 'Password',
        label: 'Password',
        type: 'string',
        required: false,
      },
    ],
    read: false,
  },
  'LoginServiceService.GetUserDetails': {
    id: 'LoginServiceService.GetUserDetails',
    title: 'Get User Details',
    method: 'GET',
    path: '/User/GetUserMasterDetailsforConfig',
    query: {
      UserName: 'UserName',
    },
    fields: [
      {
        name: 'UserName',
        label: 'User Name',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'MasterDataService.GetallPlan': {
    id: 'MasterDataService.GetallPlan',
    title: 'List Plan',
    method: 'GET',
    path: '/MasterData/ListPlanMaster',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.GetAllCompanyTypeMaster': {
    id: 'MasterDataService.GetAllCompanyTypeMaster',
    title: 'List Company Type Master',
    method: 'GET',
    path: '/MasterData/GetAllCompanyTypeMaster',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.GenderList': {
    id: 'MasterDataService.GenderList',
    title: 'Gender List',
    method: 'GET',
    path: '/MasterData/GenderList',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.MaritalStatusList': {
    id: 'MasterDataService.MaritalStatusList',
    title: 'Marital Status List',
    method: 'GET',
    path: '/MasterData/MaritalStatusList',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.AdressTypeList': {
    id: 'MasterDataService.AdressTypeList',
    title: 'Adress Type List',
    method: 'GET',
    path: '/MasterData/AdressTypeList',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.AgencyList': {
    id: 'MasterDataService.AgencyList',
    title: 'Agency List',
    method: 'GET',
    path: '/MasterData/AgencyList',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.BankList': {
    id: 'MasterDataService.BankList',
    title: 'Bank List',
    method: 'GET',
    path: '/MasterData/BankList',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.StateList': {
    id: 'MasterDataService.StateList',
    title: 'State List',
    method: 'GET',
    path: '/MasterData/StateList',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.DistrictList': {
    id: 'MasterDataService.DistrictList',
    title: 'District List',
    method: 'GET',
    path: '/MasterData/DistrictList',
    query: {
      StateId: 'StateId',
    },
    fields: [
      {
        name: 'StateId',
        label: 'State ID',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'MasterDataService.DistrictMasterList': {
    id: 'MasterDataService.DistrictMasterList',
    title: 'District Master List',
    method: 'POST',
    path: '/MasterData/DistrictMasterList',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'StateId',
        label: 'State ID',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
  'MasterDataService.KycTypeList': {
    id: 'MasterDataService.KycTypeList',
    title: 'Kyc Type List',
    method: 'GET',
    path: '/MasterData/KycTypeList',
    query: {
      CompanyTypeId: 'CompanyTypeId',
      UserTypeID: 'UserTypeID',
    },
    fields: [
      {
        name: 'CompanyTypeId',
        label: 'Company Type ID',
        type: 'string',
        required: true,
      },
      {
        name: 'UserTypeID',
        label: 'User Type ID',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'MasterDataService.UserTypeList': {
    id: 'MasterDataService.UserTypeList',
    title: 'User Type List',
    method: 'GET',
    path: '/MasterData/UserTypeList',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.UserTypeAdminList': {
    id: 'MasterDataService.UserTypeAdminList',
    title: 'User Type Admin List',
    method: 'GET',
    path: '/MasterData/UserTypeAdminList',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.DemographicDataListByPincode': {
    id: 'MasterDataService.DemographicDataListByPincode',
    title: 'Demographic Data List By Pincode',
    method: 'GET',
    path: '/MasterData/DemographicDataListByPincode',
    query: {
      Pincode: 'Pincode',
    },
    fields: [
      {
        name: 'Pincode',
        label: 'Pincode',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'MasterDataService.DemographicDataListByPincodeList': {
    id: 'MasterDataService.DemographicDataListByPincodeList',
    title: 'Demographic Data List By Pincode List',
    method: 'POST',
    path: '/MasterData/DemographicDataListByPincodeList',
    query: {},
    fields: [
      {
        name: 'PageNo',
        label: 'Page No',
        type: 'number',
        required: true,
        default: 1,
      },
      {
        name: 'PageSize',
        label: 'Page Size',
        type: 'number',
        required: true,
        default: 20,
      },
      {
        name: 'OrderBy',
        label: 'Order By',
        type: 'string',
        required: false,
      },
      {
        name: 'Pincode',
        label: 'Pincode',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'MasterDataService.ListLedegrType': {
    id: 'MasterDataService.ListLedegrType',
    title: 'List Ledegr Type',
    method: 'GET',
    path: '/MasterData/ListLedegrType',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.ListServiceType': {
    id: 'MasterDataService.ListServiceType',
    title: 'List Service Type',
    method: 'GET',
    path: '/MasterData/ListServiceType',
    query: {
      AgencyId: 'AgencyId',
    },
    fields: [
      {
        name: 'AgencyId',
        label: 'Agency ID',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'MasterDataService.ListPaymentChanel': {
    id: 'MasterDataService.ListPaymentChanel',
    title: 'List Payment Chanel',
    method: 'GET',
    path: '/MasterData/ListPaymentChanel',
    query: {},
    fields: [],
    read: true,
  },
  'MasterDataService.ListPaymentModes': {
    id: 'MasterDataService.ListPaymentModes',
    title: 'List Payment Modes',
    method: 'GET',
    path: '/MasterData/ListPaymentModes',
    query: {
      PaymentChanelId: 'PaymentChanelId',
    },
    fields: [
      {
        name: 'PaymentChanelId',
        label: 'Payment Chanel ID',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'MasterDataService.ListAllService': {
    id: 'MasterDataService.ListAllService',
    title: 'List All Service',
    method: 'GET',
    path: '/MasterData/ListAllService',
    query: {
      ServiceTypeId: 'ServiceTypeId',
    },
    fields: [
      {
        name: 'ServiceTypeId',
        label: 'Service Type ID',
        type: 'string',
        required: true,
      },
    ],
    read: true,
  },
  'SysMgrService.CreateNewRoles': {
    id: 'SysMgrService.CreateNewRoles',
    title: 'Create New Roles',
    method: 'POST',
    path: '/SysMgr/CreateNewRole',
    query: {},
    fields: [
      {
        name: 'RoleName',
        label: 'Role Name',
        type: 'string',
        required: true,
      },
      {
        name: 'RoleDescription',
        label: 'Role Description',
        type: 'string',
        required: true,
      },
    ],
    read: false,
  },
  'SysMgrService.GetallRoles': {
    id: 'SysMgrService.GetallRoles',
    title: 'List Roles',
    method: 'POST',
    path: '/SysMgr/GetAllRoles',
    query: {},
    fields: [
      {
        name: 'RoleName',
        label: 'Role Name',
        type: 'string',
        required: true,
      },
      {
        name: 'RoleID',
        label: 'Role ID',
        type: 'number',
        required: true,
      },
      {
        name: 'Status',
        label: 'Status',
        type: 'number',
        required: true,
      },
    ],
    read: true,
  },
};
