import type { PageDefinition } from '../core/types';
export const pages: PageDefinition[] = [
  { path: '/Dashboard/PayinRequestList', title: 'Pay-in requests', group: 'Wallet', component: 'PayinRequestListPage', source: 'src/pages/Wallet/PayinRequestListPage.tsx', operations: [], defaults: {}, columns: [] },
  { path: '/Dashboard/ServicePolicy', title: 'Service Policy', group: 'Configuration', component: 'ServicePolicyPage', source: 'src/pages/Configuration/ServicePolicyPage.tsx', operations: [], defaults: {}, columns: [] },
  ...['', '/Create', '/View', '/Edit'].map(suffix => ({
    path: '/Dashboard/payacclist' + suffix, title: 'Payment Accounts', group: 'Masters',
    component: 'PaymentAccountPage', source: 'src/pages/Masters/PaymentAccountPage.tsx',
    operations: [], defaults: {}, columns: [],
  })),
  ...[
    { path: '/Dashboard/chrgdedutype', title: 'Charge Deduction Types', component: 'ChargeDeductionTypePage' },
    { path: '/Dashboard/slabtype', title: 'Slab Types', component: 'SlabTypePage' },
  ].flatMap(page => ['', '/Create', '/View', '/Edit'].map(suffix => ({
    ...page, path: page.path + suffix, group: 'Masters',
    source: `src/pages/Masters/${page.component}.tsx`, operations: [], defaults: {}, columns: [],
  }))),
  ...['SMSGatewayList', 'SMS/Create', 'SMS/View', 'SMS/Edit'].map((suffix, index) => ({
    path: '/Dashboard/Notifications/' + suffix,
    title: ['SMS gateways', 'Create SMS gateway', 'SMS gateway details', 'Edit SMS gateway'][index],
    group: 'Notifications',
    component: [
      'SMSGatewayListPage',
      'CreateSMSGatewayPage',
      'SMSGatewayPage',
      'EditSMSGatewayPage',
    ][index],
    source: 'src/pages/Notifications',
    operations: [],
    defaults: {},
    columns: [],
  })),
  ...['', '/Create', '/View', '/Edit'].map((suffix) => ({
    path: '/Dashboard/Notifications' + (suffix || '/EmailGatwayList'),
    title: suffix ? `${suffix.slice(1)} email gateway` : 'Notification email gateways',
    group: 'Notifications',
    component:
      suffix === '/Create'
        ? 'CreateEmailGatewayPage'
        : suffix === '/Edit'
          ? 'EditEmailGatewayPage'
          : suffix === '/View'
            ? 'EmailGatewayPage'
            : 'NotificationsPage',
    source: 'src/pages/Notifications',
    operations: [],
    defaults: {},
    columns: [],
  })),
  {
    path: '/Dashboard/Notifications/TemplateTypes',
    title: 'Notification template types',
    group: 'Notifications',
    component: 'TemplateTypeListPage',
    source: 'src/pages/Notifications',
    operations: [],
    defaults: {},
    columns: [],
  },
  {
    path: '/Dashboard/Notifications/TemplateTypes/Create',
    title: 'Create notification template type',
    group: 'Notifications',
    component: 'CreateTemplateTypePage',
    source: 'src/pages/Notifications',
    operations: [],
    defaults: {},
    columns: [],
  },
  {
    path: '/Dashboard/Notifications/ServiceTypes',
    title: 'Notification service types',
    group: 'Notifications',
    component: 'ServiceTypeListPage',
    source: 'src/pages/Notifications',
    operations: [],
    defaults: { AgencyId: 0 },
    columns: [],
  },
  {
    path: '/Dashboard/Notifications/ServiceTypes/Create',
    title: 'Create notification service type',
    group: 'Notifications',
    component: 'CreateServiceTypePage',
    source: 'src/pages/Notifications',
    operations: [],
    defaults: {},
    columns: [],
  },
  ...['', '/Create', '/View', '/Edit'].map((suffix) => ({
    path: '/Dashboard/Notifications/Templates' + suffix,
    title: suffix ? `${suffix.slice(1)} notification template` : 'Notification templates',
    group: 'Notifications',
    component:
      suffix === '/Create'
        ? 'CreateTemplatePage'
        : suffix === '/Edit'
          ? 'EditTemplatePage'
          : suffix === '/View'
            ? 'TemplatePage'
            : 'TemplateListPage',
    source: 'src/pages/Notifications',
    operations: [],
    defaults: {},
    columns: [],
  })),
  {
    path: '/Dashboard/UserDashboard',
    title: 'User Dashboard',
    group: 'common',
    component: 'UserDashboardPage',
    source: 'src/components/UserDashboard.tsx',
    operations: [
      'LoginServiceService.GetUserDetails',
      'ReportmanService.GetDayBookByUserId',
      'ReportmanService.PayoutTransactionReport',
    ],
    defaults: {},
    columns: [],
  },
  {
    path: '/forget',
    title: 'Forgetpwd',
    group: 'common',
    component: 'ForgetpwdPage',
    source: 'src/app/component/common/forgetpwd/forgetpwd.component.ts',
    operations: [],
    defaults: {},
    columns: [],
  },
  {
    path: '/login',
    title: 'Login',
    group: 'common',
    component: 'LoginPage',
    source: 'src/app/component/common/login/login.component.ts',
    operations: ['LoginServiceService.login', 'LoginServiceService.GetUserDetails'],
    defaults: {},
    columns: [],
  },
  {
    path: '/Dashboard/CommissionType',
    title: 'Plan Type List',
    group: 'Masters',
    component: 'CommissiontypePage',
    source: 'src/app/component/Masters/commissiontype/commissiontype.component.ts',
    operations: ['MasterDataService.GetallPlan'],
    defaults: {},
    columns: ['PlanID', 'StatusName', 'PlanName'],
  },
  ...['', '/Create', '/View', '/Edit'].map(suffix => ({
    path: '/Dashboard/CalculationType' + suffix, title: 'Calculation Types', group: 'Masters',
    component: 'CalculationTypePage', source: 'src/pages/Masters/CalculationTypePage.tsx',
    operations: [], defaults: {}, columns: ['CalculationTypeId', 'CalculationTypeName', 'StatusName'],
  })),
  {
    path: '/Dashboard/CompanyType',
    title: 'Company Type List',
    group: 'Masters',
    component: 'CompanymasterPage',
    source: 'src/app/component/Masters/companymaster/companymaster.component.ts',
    operations: ['MasterDataService.GetAllCompanyTypeMaster'],
    defaults: {},
    columns: ['CompnayTypeId', 'CompanyTypeName', 'StatusName'],
  },
  {
    path: '/Dashboard/Gender',
    title: 'Gender List',
    group: 'Masters',
    component: 'GenderPage',
    source: 'src/app/component/Masters/gender/gender.component.ts',
    operations: ['MasterDataService.GenderList'],
    defaults: {},
    columns: ['GenderId', 'GenderName'],
  },
  {
    path: '/Dashboard/MaritalStatus',
    title: 'Marital Status List',
    group: 'Masters',
    component: 'MaritalStatusPage',
    source: 'src/app/component/Masters/marital-status/marital-status.component.ts',
    operations: ['MasterDataService.MaritalStatusList'],
    defaults: {},
    columns: ['MaritalStatusID', 'MaritalStatusName'],
  },
  {
    path: '/Dashboard/AddressType',
    title: 'Address Type List',
    group: 'Masters',
    component: 'AddresstypePage',
    source: 'src/app/component/Masters/addresstype/addresstype.component.ts',
    operations: ['MasterDataService.AdressTypeList'],
    defaults: {},
    columns: ['AddressTypeId', 'AddressTypeName', 'StatusName'],
  },
  {
    path: '/Dashboard/Agency',
    title: 'Agency List',
    group: 'Masters',
    component: 'AgencyPage',
    source: 'src/app/component/Masters/agency/agency.component.ts',
    operations: ['MasterDataService.AgencyList'],
    defaults: {},
    columns: ['AgencyId', 'AgencyCode', 'AgencyName', 'StatusName'],
  },
  {
    path: '/Dashboard/BankMaster',
    title: 'Bank List',
    group: 'Masters',
    component: 'BankMasterrPage',
    source: 'src/app/component/Masters/bank-masterr/bank-masterr.component.ts',
    operations: ['MasterDataService.BankList'],
    defaults: {},
    columns: ['BankID', 'BankName', 'StatusName'],
  },
  {
    path: '/Dashboard/StateMaster',
    title: 'State List',
    group: 'Masters',
    component: 'StateMasterPage',
    source: 'src/app/component/Masters/state-master/state-master.component.ts',
    operations: ['MasterDataService.StateList'],
    defaults: {},
    columns: ['StateID', 'StateCode', 'StateName'],
  },
  {
    path: '/Dashboard/DistrictMaster',
    title: 'District Master',
    group: 'Masters',
    component: 'DistrictMasterPage',
    source: 'src/app/component/Masters/district-master/district-master.component.ts',
    operations: ['MasterDataService.StateList', 'MasterDataService.DistrictMasterList'],
    defaults: {
      PageNo: 1,
      PageSize: 10,
    },
    columns: ['DistrictID', 'DistrictCode', 'DistrictName', 'StateName'],
  },
  {
    path: '/Dashboard/KycTypeMaster',
    title: 'KYC Type Master',
    group: 'Masters',
    component: 'KYCTypeMasterPage',
    source: 'src/app/component/Masters/kyctype-master/kyctype-master.component.ts',
    operations: [
      'MasterDataService.GetAllCompanyTypeMaster',
      'MasterDataService.UserTypeList',
      'MasterDataService.KycTypeList',
    ],
    defaults: {},
    columns: ['KycTypeID', 'UserTypeName', 'CompanyTypeName', 'KycTypeName'],
  },
  {
    path: '/Dashboard/UserTypeMaster',
    title: 'User Type List',
    group: 'Masters',
    component: 'UserTypeMasterPage',
    source: 'src/app/component/Masters/user-type-master/user-type-master.component.ts',
    operations: ['MasterDataService.UserTypeList'],
    defaults: {},
    columns: ['UserTypeId', 'UserTypeName', 'StatusName'],
  },
  {
    path: '/Dashboard/DemographicDetail',
    title: 'Demographic Details',
    group: 'Masters',
    component: 'DemographicMasterPage',
    source: 'src/app/component/Masters/demographic-master/demographic-master.component.ts',
    operations: ['MasterDataService.DemographicDataListByPincodeList'],
    defaults: {
      PageNo: 1,
      PageSize: 10,
    },
    columns: [
      'PincodeDataId',
      'StateName',
      'DistrictName',
      'SubDistrictName',
      'AreaName',
      'Pincode',
    ],
  },
  {
    path: '/Dashboard/LedgerType',
    title: 'Ledger Type List',
    group: 'Masters',
    component: 'LedgerTypeMasterPage',
    source: 'src/app/component/Masters/ledger-type-master/ledger-type-master.component.ts',
    operations: ['MasterDataService.ListLedegrType'],
    defaults: {},
    columns: ['LedgerTypeId', 'LedgerTypeName', 'StatusName'],
  },
  {
    path: '/Dashboard/ServiceType',
    title: 'Service Type Master',
    group: 'Masters',
    component: 'ServiceTypeMasterPage',
    source: 'src/app/component/Masters/service-type-master/service-type-master.component.ts',
    operations: ['MasterDataService.AgencyList', 'MasterDataService.ListServiceType'],
    defaults: {},
    columns: ['ServiceTypeId', 'AgencyName', 'ServiceTypeName'],
  },
  {
    path: '/Dashboard/PaymentChanel',
    title: 'Payment Chanel List',
    group: 'Masters',
    component: 'PaymentChanelPage',
    source: 'src/app/component/Masters/payment-chanel/payment-chanel.component.ts',
    operations: ['MasterDataService.ListPaymentChanel'],
    defaults: {},
    columns: ['PaymentChanelID', 'PaymentChanelName'],
  },
  {
    path: '/Dashboard/PaymentMode',
    title: 'Payment Mode Master',
    group: 'Masters',
    component: 'PaymentModeMasterPage',
    source: 'src/app/component/Masters/payment-mode-master/payment-mode-master.component.ts',
    operations: ['MasterDataService.ListPaymentChanel', 'MasterDataService.ListPaymentModes'],
    defaults: {},
    columns: ['PaymentModeID', 'PaymentChanelName', 'PaymentModeName', 'StatusName'],
  },
  {
    path: '/Dashboard/AppMgr',
    title: 'Application List',
    group: 'APIM',
    component: 'AppManagerPage',
    source: 'src/pages/AppManager/AppManagerPage.tsx',
    operations: ['UserMasterService.ListApplication', 'UserMasterService.CreateNewApplication'],
    defaults: {},
    columns: [
      'ApplicationID',
      'OrganisationName',
      'EmailId',
      'MobileNo',
      'ApplicationName',
      'ApplicationToken',
      'StatusName',
    ],
  },
  {
    path: '/Dashboard/MenuMgr',
    title: 'Menu Master',
    group: 'APIM',
    component: 'MenuMasterPage',
    source: 'src/pages/AppManager/MenuMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['MenuID', 'ModuleID', 'ModuleName', 'ParentID', 'Title', 'RoutePath', 'StatusName'],
  },
  {
    path: '/Dashboard/ModuleMgr',
    title: 'Module Master',
    group: 'APIM',
    component: 'ModuleMasterPage',
    source: 'src/pages/AppManager/ModuleMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['ModuleID', 'ApplicationID', 'ApplicationName', 'ModuleName', 'DefaultMenuUrl', 'StatusName'],
  },
  {
    path: '/Dashboard/PayoutTxnrpt',
    title: 'Transaction Report',
    group: 'Reports',
    component: 'TransactionReportPage',
    source: 'src/app/component/Reports/transaction-report/transaction-report.component.ts',
    operations: ['ReportmanService.PayoutTransactionReport'],
    defaults: {
      PageNo: 1,
      PageSize: 10,
    },
    columns: [
      'BankTxnDatetime',
      'Amount',
      'RefNo',
      'RelatedReference',
      'PartnerName',
      'PartnerTxnId',
      'RefNo1',
      'FailureReason',
    ],
  },
  {
    path: '/Dashboard/stmtrpt',
    title: 'Statement Report',
    group: 'Reports',
    component: 'UsrStatementPage',
    source: 'src/app/component/Reports/usr-statement/usr-statement.component.ts',
    operations: ['ReportmanService.ListUserStatement'],
    defaults: {
      PageNo: 1,
      PageSize: 10,
    },
    columns: [
      'LedgerId',
      'LedgerDate',
      'OrganisationName',
      'LedgerTypeName',
      'Naration',
      'DbCr',
      'Amount',
      'Limit',
      'ReferenceId',
    ],
  },
  {
    path: '/Dashboard/payinReport',
    title: 'Pay in Report',
    group: 'Reports',
    component: 'PayinRequestReportPage',
    source: 'src/app/component/Reports/payin-request-report/payin-request-report.component.ts',
    operations: ['TransactionsService.ListPaymentResponse'],
    defaults: {
      PageNo: 1,
      PageSize: 10,
    },
    columns: [
      'RequestID',
      'CreatedOn',
      'DepositDate',
      'PaymentChanelName',
      'PaymentModeName',
      'AccountName',
      'AccountNo',
      'RefNo1',
      'RefNo2',
      'RejectedReason',
      'Remarks',
      'StatusName',
      'CreatedBy',
      'UpdatedOn',
      'UpdatedBy',
    ],
  },
  {
    path: '/Dashboard/Commdistr',
    title: 'Commission Distributions',
    group: 'Configuration',
    component: 'DistributionCommissionPage',
    source: 'src/pages/Configuration/DistributionCommissionPage.tsx',
    operations: [], defaults: {}, columns: [],
  },
  {
    path: '/Dashboard/servicemst',
    title: 'Service List',
    group: 'Configuration',
    component: 'ServiceListPage',
    source: 'src/app/component/Configuration/service-list/service-list.component.ts',
    operations: ['MasterDataService.ListAllService'],
    defaults: {},
    columns: [
      'ServiceId',
      'ServiceTypeName',
      'ServiceCode',
      'ServiceName',
      'ServiceAccountNo',
      'ServcieIfsccode',
      'ServiceAccName',
      'ServiceMobileNo',
    ],
  },
  {
    path: '/Dashboard/topupcrglist',
    title: 'Top-up Charges',
    group: 'Configuration',
    component: 'TopupChargeListPage',
    source: 'src/pages/Configuration/TopupChargeListPage.tsx',
    operations: [], defaults: {}, columns: [],
  },
  {
    path: '/Dashboard/txtslablist',
    title: 'Transaction Slabs',
    group: 'Configuration',
    component: 'TransactionSlablistPage',
    source: 'src/pages/Configuration/TransactionSlablistPage.tsx',
    operations: [], defaults: {}, columns: [],
  },
  {
    path: '/Dashboard/addtxnslab',
    title: 'Add Transaction Slab',
    group: 'Configuration',
    component: 'AddTransactionSlabPage',
    source: 'src/pages/Configuration/AddTransactionSlabPage.tsx',
    operations: [], defaults: {}, columns: [],
  },
  {
    path: '/Dashboard/RoleMgr',
    title: 'Role Master',
    group: 'AccessManager',
    component: 'RoleMasterPage',
    source: 'src/pages/AppManager/RoleMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['RoleID', 'IconID', 'RoleName', 'RoleDescription', 'StatusName'],
  },
  {
    path: '/Dashboard/TaskMgr',
    title: 'Task Master',
    group: 'AccessManager',
    component: 'TaskMasterPage',
    source: 'src/pages/AppManager/TaskMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['TaskID', 'TaskName', 'TaskTooltip', 'EntityTypeID', 'TaskURI', 'StatusName'],
  },
  {
    path: '/Dashboard/PermissionMgr',
    title: 'Permission Master',
    group: 'AccessManager',
    component: 'PermissionMasterPage',
    source: 'src/pages/AppManager/PermissionMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['PermissionID', 'PermissionName', 'PermissionDescription', 'StatusName'],
  },
  {
    path: '/Dashboard/MenuPermissionMgr',
    title: 'Menu Permission Master',
    group: 'AccessManager',
    component: 'MenuPermissionMasterPage',
    source: 'src/pages/AppManager/MenuPermissionMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['MenuPermissionID', 'MenuID', 'MenuName', 'PermissionID', 'PermissionName', 'StatusName'],
  },
  {
    path: '/Dashboard/RolePermissionMgr',
    title: 'Role Permission Master',
    group: 'AccessManager',
    component: 'RolePermissionMasterPage',
    source: 'src/pages/AppManager/RolePermissionMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['RolePermissionID', 'RoleID', 'RoleName', 'PermissionID', 'PermissionName', 'StatusName'],
  },
  {
    path: '/Dashboard/RoleTaskMgr',
    title: 'Role Task Master',
    group: 'AccessManager',
    component: 'RoleTaskMasterPage',
    source: 'src/pages/AppManager/RoleTaskMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['RoleTaskID', 'RoleID', 'RoleName', 'TaskID', 'TaskName', 'ModuleName', 'TAT', 'StatusName'],
  },
  {
    path: '/Dashboard/UserMasterlst',
    title: 'User Master',
    group: 'UserManager',
    component: 'UserMasterPage',
    source: 'src/pages/Usermanager/UserMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['UserMasterID', 'UserName', 'FirstName', 'LastName', 'OrganizationName', 'UserTypeName', 'EmailId', 'MobileNo', 'StatusName'],
  },
  {
    path: '/Dashboard/OrgMgr',
    title: 'Organization Master',
    group: 'OrgManager',
    component: 'OrgMgrMasterPage',
    source: 'src/pages/OrgManager/OrgMgrMasterPage.tsx',
    operations: [],
    defaults: {},
    columns: ['OrganizationID', 'OrganizationCode', 'OrganizationName', 'DisplayName', 'OrganizationTypeID', 'Email', 'MobileNo', 'StatusName'],
  },
];
