import { lazy } from 'react';
export const routeComponents = {
  '/Dashboard/payacclist': lazy(() => import('../pages/Masters/PaymentAccountPage')),
  '/Dashboard/payacclist/Create': lazy(() => import('../pages/Masters/PaymentAccountPage')),
  '/Dashboard/payacclist/View': lazy(() => import('../pages/Masters/PaymentAccountPage')),
  '/Dashboard/payacclist/Edit': lazy(() => import('../pages/Masters/PaymentAccountPage')),
  '/Dashboard/chrgdedutype': lazy(() => import('../pages/Masters/ChargeDeductionTypePage')),
  '/Dashboard/chrgdedutype/Create': lazy(() => import('../pages/Masters/ChargeDeductionTypePage')),
  '/Dashboard/chrgdedutype/View': lazy(() => import('../pages/Masters/ChargeDeductionTypePage')),
  '/Dashboard/chrgdedutype/Edit': lazy(() => import('../pages/Masters/ChargeDeductionTypePage')),
  '/Dashboard/slabtype': lazy(() => import('../pages/Masters/SlabTypePage')),
  '/Dashboard/slabtype/Create': lazy(() => import('../pages/Masters/SlabTypePage')),
  '/Dashboard/slabtype/View': lazy(() => import('../pages/Masters/SlabTypePage')),
  '/Dashboard/slabtype/Edit': lazy(() => import('../pages/Masters/SlabTypePage')),
  '/Dashboard/Notifications/SMSGatewayList': lazy(
    () => import('../pages/Notifications/SMSGatewayListPage'),
  ),
  '/Dashboard/Notifications/SMS/Create': lazy(
    () => import('../pages/Notifications/CreateSMSGatewayPage'),
  ),
  '/Dashboard/Notifications/SMS/View': lazy(() => import('../pages/Notifications/SMSGatewayPage')),
  '/Dashboard/Notifications/SMS/Edit': lazy(
    () => import('../pages/Notifications/EditSMSGatewayPage'),
  ),
  '/Dashboard/Notifications/EmailGatwayList': lazy(
    () => import('../pages/Notifications/NotificationsPage'),
  ),
  '/Dashboard/Notifications/Create': lazy(
    () => import('../pages/Notifications/CreateEmailGatewayPage'),
  ),
  '/Dashboard/Notifications/View': lazy(() => import('../pages/Notifications/EmailGatewayPage')),
  '/Dashboard/Notifications/Edit': lazy(
    () => import('../pages/Notifications/EditEmailGatewayPage'),
  ),
  '/Dashboard/Notifications/Templates': lazy(
    () => import('../pages/Notifications/TemplateListPage'),
  ),
  '/Dashboard/Notifications/Templates/Create': lazy(
    () => import('../pages/Notifications/CreateTemplatePage'),
  ),
  '/Dashboard/Notifications/Templates/View': lazy(
    () => import('../pages/Notifications/TemplatePage'),
  ),
  '/Dashboard/Notifications/Templates/Edit': lazy(
    () => import('../pages/Notifications/EditTemplatePage'),
  ),
  '/Dashboard/Notifications/TemplateTypes': lazy(
    () => import('../pages/Notifications/TemplateTypeListPage'),
  ),
  '/Dashboard/Notifications/TemplateTypes/Create': lazy(
    () => import('../pages/Notifications/CreateTemplateTypePage'),
  ),
  '/Dashboard/Notifications/ServiceTypes': lazy(
    () => import('../pages/Notifications/NotificationServiceTypePage'),
  ),
  '/Dashboard/Notifications/ServiceTypes/Create': lazy(
    () => import('../pages/Notifications/CreateServiceTypePage'),
  ),
  '/Dashboard/UserDashboard': lazy(() => import('../pages/AppMain/UserDashboardPage')),
  '/Dashboard/CommissionType': lazy(() => import('../pages/Masters/CommissiontypePage')),
  '/Dashboard/CommissionType/Create': lazy(() => import('../pages/Masters/CommissiontypePage')),
  '/Dashboard/CommissionType/View': lazy(() => import('../pages/Masters/CommissiontypePage')),
  '/Dashboard/CommissionType/Edit': lazy(() => import('../pages/Masters/CommissiontypePage')),
  '/Dashboard/CalculationType': lazy(() => import('../pages/Masters/CalculationTypePage')),
  '/Dashboard/CalculationType/Create': lazy(() => import('../pages/Masters/CalculationTypePage')),
  '/Dashboard/CalculationType/View': lazy(() => import('../pages/Masters/CalculationTypePage')),
  '/Dashboard/CalculationType/Edit': lazy(() => import('../pages/Masters/CalculationTypePage')),
  '/Dashboard/CompanyType': lazy(() => import('../pages/Masters/CompanymasterPage')),
  '/Dashboard/CompanyType/Create': lazy(() => import('../pages/Masters/CompanymasterPage')),
  '/Dashboard/CompanyType/View': lazy(() => import('../pages/Masters/CompanymasterPage')),
  '/Dashboard/CompanyType/Edit': lazy(() => import('../pages/Masters/CompanymasterPage')),
  '/Dashboard/Gender': lazy(() => import('../pages/Masters/GenderPage')),
  '/Dashboard/MaritalStatus': lazy(() => import('../pages/Masters/MaritalStatusPage')),
  '/Dashboard/AddressType': lazy(() => import('../pages/Masters/AddresstypePage')),
  '/Dashboard/AddressType/Create': lazy(() => import('../pages/Masters/AddresstypePage')),
  '/Dashboard/AddressType/View': lazy(() => import('../pages/Masters/AddresstypePage')),
  '/Dashboard/AddressType/Edit': lazy(() => import('../pages/Masters/AddresstypePage')),
  '/Dashboard/Agency': lazy(() => import('../pages/Masters/AgencyPage')),
  '/Dashboard/Agency/Create': lazy(() => import('../pages/Masters/AgencyPage')),
  '/Dashboard/Agency/View': lazy(() => import('../pages/Masters/AgencyPage')),
  '/Dashboard/Agency/Edit': lazy(() => import('../pages/Masters/AgencyPage')),
  '/Dashboard/BankMaster': lazy(() => import('../pages/Masters/BankMasterrPage')),
  '/Dashboard/BankMaster/Create': lazy(() => import('../pages/Masters/BankMasterrPage')),
  '/Dashboard/BankMaster/View': lazy(() => import('../pages/Masters/BankMasterrPage')),
  '/Dashboard/BankMaster/Edit': lazy(() => import('../pages/Masters/BankMasterrPage')),
  '/Dashboard/StateMaster': lazy(() => import('../pages/Masters/StateMasterPage')),
  '/Dashboard/StateMaster/Create': lazy(() => import('../pages/Masters/StateMasterPage')),
  '/Dashboard/StateMaster/View': lazy(() => import('../pages/Masters/StateMasterPage')),
  '/Dashboard/StateMaster/Edit': lazy(() => import('../pages/Masters/StateMasterPage')),
  '/Dashboard/DistrictMaster': lazy(() => import('../pages/Masters/DistrictMasterPage')),
  '/Dashboard/DistrictMaster/Create': lazy(() => import('../pages/Masters/DistrictMasterPage')),
  '/Dashboard/DistrictMaster/View': lazy(() => import('../pages/Masters/DistrictMasterPage')),
  '/Dashboard/DistrictMaster/Edit': lazy(() => import('../pages/Masters/DistrictMasterPage')),
  '/Dashboard/KycTypeMaster': lazy(() => import('../pages/Masters/KYCTypeMasterPage')),
  '/Dashboard/KycTypeMaster/Create': lazy(() => import('../pages/Masters/KYCTypeMasterPage')),
  '/Dashboard/KycTypeMaster/View': lazy(() => import('../pages/Masters/KYCTypeMasterPage')),
  '/Dashboard/KycTypeMaster/Edit': lazy(() => import('../pages/Masters/KYCTypeMasterPage')),
  '/Dashboard/UserTypeMaster': lazy(() => import('../pages/Masters/UserTypeMasterPage')),
  '/Dashboard/UserTypeMaster/Create': lazy(() => import('../pages/Masters/UserTypeMasterPage')),
  '/Dashboard/UserTypeMaster/View': lazy(() => import('../pages/Masters/UserTypeMasterPage')),
  '/Dashboard/UserTypeMaster/Edit': lazy(() => import('../pages/Masters/UserTypeMasterPage')),
  '/Dashboard/DemographicDetail': lazy(() => import('../pages/Masters/DemographicMasterPage')),
  '/Dashboard/LedgerType': lazy(() => import('../pages/Masters/LedgerTypeMasterPage')),
  '/Dashboard/LedgerType/Create': lazy(() => import('../pages/Masters/LedgerTypeMasterPage')),
  '/Dashboard/LedgerType/View': lazy(() => import('../pages/Masters/LedgerTypeMasterPage')),
  '/Dashboard/LedgerType/Edit': lazy(() => import('../pages/Masters/LedgerTypeMasterPage')),
  '/Dashboard/ServiceType': lazy(() => import('../pages/Masters/ServiceTypeMasterPage')),
  '/Dashboard/ServiceType/Create': lazy(() => import('../pages/Masters/ServiceTypeMasterPage')),
  '/Dashboard/ServiceType/View': lazy(() => import('../pages/Masters/ServiceTypeMasterPage')),
  '/Dashboard/ServiceType/Edit': lazy(() => import('../pages/Masters/ServiceTypeMasterPage')),
  '/Dashboard/PaymentChanel': lazy(() => import('../pages/Masters/PaymentChanelPage')),
  '/Dashboard/PaymentChanel/Create': lazy(() => import('../pages/Masters/PaymentChanelPage')),
  '/Dashboard/PaymentChanel/View': lazy(() => import('../pages/Masters/PaymentChanelPage')),
  '/Dashboard/PaymentChanel/Edit': lazy(() => import('../pages/Masters/PaymentChanelPage')),
  '/Dashboard/PaymentMode': lazy(() => import('../pages/Masters/PaymentModeMasterPage')),
  '/Dashboard/PaymentMode/Create': lazy(() => import('../pages/Masters/PaymentModeMasterPage')),
  '/Dashboard/PaymentMode/View': lazy(() => import('../pages/Masters/PaymentModeMasterPage')),
  '/Dashboard/PaymentMode/Edit': lazy(() => import('../pages/Masters/PaymentModeMasterPage')),
  '/Dashboard/AppMgr': lazy(() => import('../pages/AppManager/AppManagerPage')),
  '/Dashboard/MenuMgr': lazy(() => import('../pages/AppManager/MenuMasterPage')),
  '/Dashboard/ModuleMgr': lazy(() => import('../pages/AppManager/ModuleMasterPage')),
  '/Dashboard/PayoutTxnrpt': lazy(() => import('../pages/Reports/TransactionReportPage')),
  '/Dashboard/stmtrpt': lazy(() => import('../pages/Reports/UsrStatementPage')),
  '/Dashboard/payinReport': lazy(() => import('../pages/Reports/PayinRequestReportPage')),
  '/Dashboard/Commdistr': lazy(() => import('../pages/Configuration/DistributionCommissionPage')),
  '/Dashboard/servicemst': lazy(() => import('../pages/Masters/ServiceListPage')),
  '/Dashboard/servicemst/Create': lazy(() => import('../pages/Masters/ServiceListPage')),
  '/Dashboard/servicemst/View': lazy(() => import('../pages/Masters/ServiceListPage')),
  '/Dashboard/servicemst/Edit': lazy(() => import('../pages/Masters/ServiceListPage')),
  '/Dashboard/topupcrglist': lazy(() => import('../pages/Configuration/TopupChargeListPage')),
  '/Dashboard/txtslablist': lazy(() => import('../pages/Configuration/TransactionSlablistPage')),
  '/Dashboard/addtxnslab': lazy(() => import('../pages/Configuration/AddTransactionSlabPage')),
  '/Dashboard/ServicePolicy': lazy(() => import('../pages/Configuration/ServicePolicyPage')),
  '/Dashboard/RoleMgr': lazy(() => import('../pages/AppManager/RoleMasterPage')),
  '/Dashboard/RoleTaskMgr': lazy(() => import('../pages/AppManager/RoleTaskMasterPage')),
  '/Dashboard/RolePermissionMgr': lazy(() => import('../pages/AppManager/RolePermissionMasterPage')),
  '/Dashboard/MenuPermissionMgr': lazy(() => import('../pages/AppManager/MenuPermissionMasterPage')),
  '/Dashboard/TaskMgr': lazy(() => import('../pages/AppManager/TaskMasterPage')),
  '/Dashboard/PermissionMgr': lazy(() => import('../pages/AppManager/PermissionMasterPage')),
  '/Dashboard/OrgMgr': lazy(() => import('../pages/OrgManager/OrgMgrMasterPage')),
  '/Dashboard/UserMasterlst': lazy(() => import('../pages/Usermanager/UserMasterPage')),
};
